apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-vault-agent-injector
  namespace: sidecar-test
  labels:
    app.kubernetes.io/name: vault-agent-injector
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
