apiVersion: v1
kind: Pod
metadata:
  name: hellovault-with-annotations
  labels:
    app: hellovault-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'hellovault-app'
    vault.hashicorp.com/agent-inject-secret-config: 'secret/data/web'
    # Environment variable export template
    vault.hashicorp.com/agent-inject-template-config: |
      {{ with secret "secret/data/web" -}}
        export APP_SERVICE1_API_KEY="{{ .Data.data.service1_api_key }}"
      {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
    - name: app
      image: mackhendricks/hellovault
      env:
      - name: VAULT_ADDR
        value: "http://external-vault:8200"
  imagePullSecrets:
    - name: myregistrykey
